import type { Metadata } from "next";
import Navbar from "@/src/app/components/Layout/Navbar";
import "./globals.css"; // ถ้ามี CSS รวมทั้งหมด

export const metadata: Metadata = {
  title: "Jirayut Dev",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="min-h-screen bg-white text-gray-900">
        <Navbar />
        <main>{children}</main>
      </body>
    </html>
  );
}
